image: python:3.14.6-trixie@sha256:cac80dc03dafb0e9ffc5d390ada6c2e8f6323a275bb89c1d132fedf7a195e054

pypi:
  stage: deploy
  id_tokens:
    PYPI_ID_TOKEN:
      aud: pypi
  script:
    - pip install build twine
    - python -m build
    - python -m twine upload dist/*
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+([abc]\d*)?$/'  # PEP-440 compliant version (tags)
