image: python:3.14.6-trixie@sha256:7a320a6d1216cd356eb4790261f2332e6e29e32f7e80646cb3e79f9e65b8e2c2

pypi:
  stage: deploy
  id_tokens:
    PYPI_ID_TOKEN:
      aud: pypi
  script:
    - pip install build twine
    - python -m build
    - python -m twine upload dist/*
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+([abc]\d*)?$/'  # PEP-440 compliant version (tags)
